blank_issues_enabled: false
contact_links:
  - name: Beekeeper Documentation
    url: https://beekeeper-ai.github.io/beekeeper
    about: Please review the latest documentation before posting an issue.