name: Deploy MkDocs to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: 3.11
      
    - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

    - name: Install dependencies
      run: poetry install --no-root
      working-directory: docs/api_reference

    - name: Build MkDocs site
      run: poetry run mkdocs build --strict
      working-directory: docs/api_reference

    - name: Setup pages
      uses: actions/configure-pages@v4
      
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/api_reference/site
        
    - id: deployment
      name: Deploy to github pages
      uses: actions/deploy-pages@v4
      