name: Deploy MkDocs to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: install uv
      uses: astral-sh/setup-uv@v6

    - name: set up Python
      run: uv python install 3.11

    - name: install dependencies
      run: uv sync --locked
      working-directory: docs/api_reference

    - name: build mkdocs
      run: uv run mkdocs build --strict
      working-directory: docs/api_reference

    - name: setup pages
      uses: actions/configure-pages@v4
      
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/api_reference/site
        
    - id: deployment
      name: deploy to github pages
      uses: actions/deploy-pages@v4
      